### ISSUE TITLE
Support of user API endpoints

### ISSUE THREAD

**Issue by patrick-cichon-gcx** [sniner/docuware-client#1]
Hey @sniner,

cool library to speak to the DocuWare API, thanks for that! 
I'd like to automate account creation and deactivation for my company and wanted to use your library. So far I cant find any references to the endpoints /Organization/Users & /Organization/UserInfo (those will be the endpoints I will be needing, I think). Those endpoints are not supported so far, correct?

Best,
Patrick

**Comment by sniner** [comment]
Hi @patrick-cichon-gcx 

you are absolutely right, the endpoints for user management are not supported yet. I'll look into it, but I can't promise anything as the Docuware REST API documentation isn't really of much good.

**Comment by patrick-cichon-gcx** [comment]
Ok cool, thanks for looking into it! Yeah no worries, I'll also check if I'll be able to contribute this to your library. Just have to see when I'll get to it.

Yeah the DocuWare documentation is pretty bad, also had trouble finding things. What I found a little more helpful is the Postman collection. This is how I found out about the User endpoints in the first place.

**Comment by patrick-cichon-gcx** [comment]
Hey @sniner,

I added the functionality that I need and some more to your library. If you want you can take a look at it. I added the following functions:
- Get user
- Get user list
- Create user
- Deactivate user
- Activate user
- Get group
- Get group list
- Add group to user
- Remove group from user

I tried to implement and integrate the new functionality as best as I could based on your logic, I hope thats ok. 
I've never contributed to a project so far. I'm not sure whats the best way for me to do this? Just open a PR for you to review?
I'd appreciate if you could assist me with this so that I can contribute this in a way that is best for you.

**Comment by sniner** [comment]
Hi @patrick-cichon-gcx 

Thank you very much for your contribution! Could you please create a pull request, then I can look at your work and add it to the project after review. If you need help with that, just ask.

**Comment by patrick-cichon-gcx** [comment]
Hey @sniner,

can you give me a rough estimate on when you'll be able to upload the new release to PyPi?

**Comment by sniner** [comment]
Hi @patrick-cichon-gcx, thanks for the reminder. It is now at PyPI as v0.2.0. Sorry for the delay.

**Comment by sniner** [comment]
Hi @patrick-cichon-gcx, thanks for the reminder. It is now at PyPI as v0.2.0. Sorry for the delay.

**Comment by patrick-cichon-gcx** [comment]
Hey @sniner,

could you upload the new version from PR #4 also to PyPi?
