### ISSUE TITLE
Upload to PyPi

### ISSUE THREAD

**Issue by patrick-cichon-gcx** [sniner/docuware-client#5]
Hey @sniner,

could you upload the latest changes from #4 to PyPi?

**Comment by patrick-cichon-gcx** [comment]
Hey @sniner,

can you give an estimate on when you would be able to upload this to PyPi? Can I assist you in any way?

**Comment by sniner** [comment]
Hi @patrick-cichon-gcx , thanks for asking. The current source code can be found in the feature branch. I would like to refactor it before publishing it on PyPI, but unfortunately I don't have the time at the moment. I expect to release it by the end of this year. You could help me by testing the refactored code before the release, as I only have a production system available and cannot test write accesses. I will get in touch with you here in advance.
