### ISSUE TITLE
OAuth2 Implementation

### ISSUE THREAD

**Issue by lukemmolnar** [sniner/docuware-client#6]
DocuWare has announced it will no longer allow authentication from third-party applications using cookies. Are there plans to implement OAuth2?

**Comment by sniner** [comment]
Hi @lukemmolnar

Thanks for reaching out with the issue. Someone had already pointed out to me that authentication is changing to OAuth2 starting with version 7.11. However, I’m not sure if the current method using session cookies will be discontinued as well.

Unfortunately, I likely won’t have access to a 7.11 installation for quite some time, so it’s difficult for me to implement OAuth2 at the moment. Maybe someone with access to that version can step in and submit a pull request for OAuth2.

**Comment by sniner** [comment]
@lukemmolnar OAuth2 is implemented starting with version 0.5.0. The package will be uploaded to PyPI shortly.

**Comment by sniner** [comment]
Uploaded 0.5.1 to PyPI. If there are any issues, please open a new one.
